### ISSUE TITLE
Repeated requests to get images

### ISSUE THREAD

**Issue by ehsaneona** [mediamonks/fast-image-sequence#22]
When I open the network, many unreasonable requests are made to display frames. Why does this happen? Isn't it enough to load each image once?
![image](https://github.com/mediamonks/fast-image-sequence/assets/44504597/247be740-ac47-46a8-85b9-f232a37b3ac0)

**Comment by ReneDrie** [comment]
Isn't your cache disabled (with DevTools open)? This is the default state I think and would cause this.

**Comment by reindernijhoff** [comment]
Hi, thanks for the feedback; I will try to fix the issues ASAP and let you know. You generally want to have the image cache ~32, to limit memory usage.

**Comment by ehsaneona** [comment]
> Isn't your cache disabled (with DevTools open)? This is the default state I think and would cause this. ![3r3lb](https://private-user-images.githubusercontent.com/1842415/328503909-d32bd56c-f154-4106-86b6-93882b4e245c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODE0NjIsIm5iZiI6MTcxNTA4MTE2MiwicGF0aCI6Ii8xODQyNDE1LzMyODUwMzkwOS1kMzJiZDU2Yy1mMTU0LTQxMDYtODZiNi05Mzg4MmI0ZTI0NWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMTEyNjAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWRkNWYyNTNmYzU1MzYyZDI5OWI0ZTI2YjhlMDg2OGEwODE4NDc4MDhjNGViYmY4OWI2NjJlN2YyMTY4N2ExZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4jUzKwiJQ23ElKID7ZBVVpYhwHeHzFN-JBxEEvQyNAI)

Hello
No, both the browser cache is active and the disk cache of each image
![image](https://github.com/mediamonks/fast-image-sequence/assets/44504597/62c5ba68-0f79-4266-91b3-0283b2ee83f0)

**Comment by SinesioMM** [comment]
> Hi, thanks for the feedback; I will try to fix the issues ASAP and let you know. You generally want to have the image cache ~32, to limit memory usage.

As Reinder suggested, you should try to avoid caching too many images. However, if you need to cache more than 32 images, you can pass `numberOfCachedImages` in the options.

**Comment by ehsaneona** [comment]
> Hi, thanks for the feedback; I will try to fix the issues ASAP and let you know. You generally want to have the image cache ~32, to limit memory usage.

Thanks, Thankful
My problem is that, for example, the main1001 photo must be loaded twice.
Thank you for your quick response

**Comment by ehsaneona** [comment]
> > Hi, thanks for the feedback; I will try to fix the issues ASAP and let you know. You generally want to have the image cache ~32, to limit memory usage.
> 
> As Reinder suggested, you should try to avoid caching too many images. However, if you need to cache more than 32 images, you can pass `numberOfCachedImages` in the options.

It does not make a difference in the final result, unfortunately. I tested both models, the numberOfCachedImages is very high, like 1000 frames, and the numberOfCachedImages is low, like 33 frames.

**Comment by reindernijhoff** [comment]
@ehsaneona You are right. I found a bug and will fix it this afternoon. I will let you know when an updated package is available.

**Comment by ehsaneona** [comment]
> @ehsaneona You are right. I found a bug and will fix it this afternoon. I will let you know when an updated package is available.

Thanks a lot 🙏

**Comment by reindernijhoff** [comment]
Can you upgrade to version 0.4.4 and check if this fixes the bug?

Please let me know if this fixed your bug. Any suggestions for improving this package are very welcome.

**Comment by ehsaneona** [comment]
Thanks, the problem is solved.
