### ISSUE TITLE
Tar loading not working

### ISSUE THREAD

**Issue by cortvi** [mediamonks/fast-image-sequence#23]
First of all, great tool, really what I was looking for.
But I'm trying to use the TAR loading function and it doesn't seem to work properly.

I'm working with Nuxt in Windows and NPM if that helps.

Keep up the great work,
thanks!

**Comment by cortvi** [comment]
Okay, may bad. I was trying for 2 days, turns out there was something wrong in the way I was creating the TAR file. Used the tool you posted (https://reindernijhoff.net/tools/tar/) and now it is working.

Sorry for the inconvenience

**Comment by reindernijhoff** [comment]
Hi, thanks for your feedback!

Is there anything I could improve regarding this? Does the documentation need to be better? More logging in debug mode?

In general, do you have any suggestions on how I could improve this package? I'd love to hear them.

**Comment by ReneDrie** [comment]
I think Mac OS always puts the files in a subfolder upon creation. I fixed that by navigating to the folder with the images in Terminal and then running this: 
`tar -cvf sequence.tar -C ./ .`

Mind the `.` at the end.

**Comment by cortvi** [comment]
Wroked like a charm, thanks!
