### ISSUE TITLE
Reuse TAR files

### ISSUE THREAD

**Issue by cortvi** [mediamonks/fast-image-sequence#27]
More a question than an issue but I hope you can bring me some light on this:

When using the same TAR file in multiple parts of a page, it gets downloaded each time. Is there a way I can download the file myself and store it to then to pass it directly to the component instead of having it download the file each time?

I'm using Nuxt if that helps.

Many thanks in advance!

**Comment by reindernijhoff** [comment]
Maybe you can load the tar and convert it to a dataURL, and use this for the tarURL of the FastImageSequence. I am not sure if this works, but I will look at it next Monday and maybe add another option to share tars between FastImageSequence renderers.

```
function blobToDataURL(blob: Blob): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = _e => resolve(reader.result as string);
    reader.onerror = _e => reject(reader.error);
    reader.onabort = _e => reject(new Error("Read aborted"));
    reader.readAsDataURL(blob);
  });
}
```
